[phases.setup]
nixPkgs = ["nodejs", "chromium"]

[phases.install]
cmds = [
  "npm install",
  "npx playwright install --with-deps chromium"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
